name: medapp_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  flutter_secure_storage: ^10.0.0
  google_fonts: ^8.0.1
  http: ^1.1.0 
  shared_preferences: ^2.5.4
  file_picker: ^10.3.10
  font_awesome_flutter: ^10.12.0
  numberpicker: ^2.1.2
  intl: ^0.19.0
  url_launcher: ^6.2.5
  zego_uikit_prebuilt_call: ^4.22.2
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.1.0
  flutter_callkit_incoming: ^2.5.8
  permission_handler: ^12.0.1
  razorpay_flutter: ^1.4.1
  webview_flutter: ^4.13.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/consultAi/
