name: medapp_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  flutter_secure_storage: ^10.0.0
  google_fonts: ^8.0.1
  http: ^1.1.0 
  shared_preferences: ^2.5.4
  file_picker: ^10.3.10
  font_awesome_flutter: ^10.12.0
  numberpicker: ^2.1.2
  intl: ^0.19.0
  url_launcher: ^6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
